apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/vitaliisaveliev/garageflow.git'
    targetRevision: main
    path: gitops/apps/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
