argocd_host           = "argocd.localhost"
ingress_nginx_version = "4.10.0"
cert_manager_version  = "v1.13.2"
argocd_version        = "6.7.8"
postgresql_version  = "15.2.2"
postgresql_password = "changeme"
