name: GitOps Lint

on:
  pull_request:
    paths:
      - "gitops/**"
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install kubeconform
        run: |
          curl -sSL -o kubeconform.tar.gz https://github.com/yannh/kubeconform/releases/download/v0.6.7/kubeconform-linux-amd64.tar.gz
          tar -xzf kubeconform.tar.gz
          sudo mv kubeconform /usr/local/bin

      - name: Lint GitOps manifests
        run: |
          kubeconform \
            -summary \
            -strict \
            -ignore-missing-schemas \
            -schema-location default \
            $(find gitops -type f -name "*.yaml")
