name: Infra as Code (Terraform)

on:
  pull_request:
    paths:
      - "iac/**"
  workflow_dispatch:
    inputs:
      apply:
        description: "Run terraform apply for platform (self-hosted runner)"
        type: boolean
        default: false

jobs:
  cluster:
    name: Ensure Cluster
    runs-on: self-hosted
    defaults:
      run:
        working-directory: iac/environments/dev-local/cluster
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply (cluster)
        run: terraform apply -auto-approve -input=false

  plan:
    name: Terraform Plan (platform)
    runs-on: self-hosted
    needs: cluster
    defaults:
      run:
        working-directory: iac/environments/dev-local/platform
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform fmt & validate
        run: |
          terraform fmt -check -recursive
          terraform init -input=false
          terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color

  apply:
    name: Terraform Apply (platform)
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.apply == true }}
    runs-on: self-hosted
    needs: cluster
    defaults:
      run:
        working-directory: iac/environments/dev-local/platform
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
