name: Infra as Code (Terraform)

on:
  pull_request:
    paths:
      - "iac/**"
  workflow_dispatch:
    inputs:
      apply:
        description: "Run terraform apply on local k3d (self-hosted runner)"
        type: boolean
        default: false

jobs:
  plan:
    name: Terraform Plan
    runs-on: self-hosted   # 👈 теперь тоже у тебя на Mac
    defaults:
      run:
        working-directory: iac/environments/dev-local/platform
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform fmt & validate
        run: |
          terraform fmt -check -recursive
          terraform init
          terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color

  apply:
    name: Terraform Apply
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.apply == true }}
    runs-on: self-hosted   # 👈 оставляем у тебя
    defaults:
      run:
        working-directory: iac/environments/dev-local/platform
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
